# docker-compose file managing Nginx and the application
# Loading some variables from the .env file:
#   - DOMAIN: DNS domain name
#   - EMAIL: Maintainer email
#   - APP_FOLDER: Directory containing the application
#   - FLASK_APP: Flask entrypoint
#   - FLASK_ENV: Flask environment

version: "3.2"

services:
  db:
    build: ./db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - db_nw
    env_file:
      - .env 
    hostname: db
    logging:
        options:
            max-size: "200k"
            max-file: "10"
  nginx:
    build:
      context: ./nginx
      args:
        DOMAIN: 'thinktogether.duckdns.org'
        EMAIL: 'zacharie.bugaud@grenoble-inp.org'
        FLASK: app
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - middle_nw
    logging:
        options:
            max-size: "200k"
            max-file: "10"

  app:
    build: ./api
    command: gunicorn --bind 0.0.0.0:5000 --workers 3 app:app
    networks:
      - db_nw
      - middle_nw
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env 
    hostname: app
    logging:
        options:
            max-size: "200k"
            max-file: "10"
      
      
networks:
  db_nw:
    ipam:
      config:
        - subnet: 10.5.0.0/16
        
  middle_nw:
   ipam:
     config:
       - subnet: 10.6.0.0/16
volumes:
  dbdata:
